<<<<<<< HEAD
<?php
$pizzeria=[
    "dia1"=>[
        ["Juan Manuel"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["J.Jordi"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
    "dia2"=>[
        ["Juanfri"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["Isa"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
    "dia3"=>[
        ["Juan Manuel"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["J.Jordi"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
    "dia4"=>[
        ["Juanfri"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["Isa"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
        
];
=======
<?php
$pizzeria=[
    "dia1"=>[
        ["Juan Manuel"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["J.Jordi"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
    "dia2"=>[
        ["Juanfri"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["Isa"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
    "dia3"=>[
        ["Juan Manuel"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["J.Jordi"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
    "dia4"=>[
        ["Juanfri"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ],
        ["Isa"=>
            ["pizza1"=>["tamaño"=>"grande","nombre"=>"capriciossa","precio"=>12.45,"cantidad"=>1]],
            ["pizza2"=>[["tamaño"=>"mediana","nombre"=>"carbonara","precio"=>13.45,"cantidad"=>1]]]
        ]
    ],
        
];
>>>>>>> 147114465e09abf56b763fc92836d0324a35af13
?>